name: F# Style Rule Suggestion
description: Suggest a new F# coding style rule
title: "[F# Style]: "
labels: ["enhancement", "f#", "style-rule"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new F# style rule! Please fill out this form as completely as possible.
        
  - type: input
    id: rule-name
    attributes:
      label: Rule Name
      description: A short, descriptive name for the rule
      placeholder: "e.g., PreferPipelineOperator"
    validations:
      required: true
      
  - type: textarea
    id: rule-description
    attributes:
      label: Rule Description
      description: Describe what the rule enforces or recommends
      placeholder: "e.g., Use the pipeline operator |> for function composition instead of nested function calls"
    validations:
      required: true
      
  - type: textarea
    id: good-example
    attributes:
      label: Good Example
      description: Provide an example of code that follows this rule
      render: fsharp
      placeholder: |
        // Good:
        [1..10]
        |> List.filter (fun x -> x % 2 = 0)
        |> List.map (fun x -> x * 2)
    validations:
      required: true
      
  - type: textarea
    id: bad-example
    attributes:
      label: Bad Example
      description: Provide an example of code that violates this rule
      render: fsharp
      placeholder: |
        // Bad:
        List.map (fun x -> x * 2) (List.filter (fun x -> x % 2 = 0) [1..10])
    validations:
      required: true
      
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Explain why this rule would be beneficial
      placeholder: "This rule improves code readability by making the data flow more clear and reducing nested function calls."
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Suggested Severity
      description: How important is it to follow this rule?
      options:
        - Error (must be followed)
        - Warning (should be followed)
        - Information (nice to follow)
        - None (optional)
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context or considerations about the rule
      placeholder: "e.g., Special cases where the rule might not apply, or specific scenarios it's designed for"
    validations:
      required: false 