name: PR Validation
on:
  pull_request:
    branches: [ master ]
    paths:
      - '**.md'
  push:
    branches: [ master ]
    paths:
      - '**.md'

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install markdown-link-check
        run: npm install -g markdown-link-check
      
      - name: Validate Documentation Links
        run: |
          find . -name "*.md" -exec markdown-link-check {} \; 